name: build-stm32f405-PYBV10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone https://github.com/micropython/micropython.git /opt/micropython
        cd /opt/micropython
        git checkout master
        git pull origin master

    - name: Install packages
      run: source /opt/micropython/tools/ci.sh && ci_stm32_setup

    - name: Bulid
      run: |
        cd /opt/micropython
        git submodule update --init
        make -C mpy-cross
        make -C ports/stm32 submodules
        git submodule update --init lib/btstack
        make -C ports/stm32/mboot BOARD=PYBV10

    - name : Upload firmware-stm32f405-PYBV10
      uses: actions/upload-artifact@master
      with:
        name: firmware-stm32f405-PYBV10
        path: /opt/micropython/ports/stm32/build-PYBV10/firmware.dfu
