name: build-stm32f405-PYBV10

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/micropython/micropython.git'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone ${{ github.event.inputs.git-address }} /opt/micropython
        cd /opt/micropython

    - name: Install packages
      run: source /opt/micropython/tools/ci.sh && ci_stm32_setup

    - name: Bulid
      run: |
        mkdir /opt/firmware
        cd /opt/micropython
        git submodule update --init
        make -C mpy-cross
        make -C ports/stm32 submodules
        git submodule update --init lib/btstack
        make -C ports/stm32 BOARD=PYBV10
        cp ports/stm32/build-PYBV10/firmware.dfu /opt/firmware
        cp ports/stm32/build-PYBV10/firmware.hex /opt/firmware
        cp ports/stm32/build-PYBV10/firmware0.bin /opt/firmware
        cp ports/stm32/build-PYBV10/firmware1.bin /opt/firmware

    - name : Upload firmware-stm32f405-PYBV10
      uses: actions/upload-artifact@master
      with:
        name: firmware-stm32f405-PYBV10
        path: /opt/firmware
